from typing import Any, Dict, Type

class Task:
    def run(self, *args: object, **kwargs: object) -> object: ...

class Celery:
    def __init__(self, name: str, task_cls: Type[Task]) -> None: ...
    def config_from_object(self, config: Dict[str, Any]) -> None: ...
    def set_default(self) -> None: ...
